### ISSUE TITLE
Setting headers for errors

### ISSUE THREAD

**Issue by rakeshpai** [articulate/paperplane#34]
When sending a 401 Unauthorized, I want to set a [WWW-Authenticate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate) header. Considering that a 401 would be handled as a promise error, what's the recommended way of setting the header?

**Comment by flintinatux** [comment]
Excellent question, and I'm sorry that we haven't documented that yet.  If you set a `headers` object on your error, `paperplane` will [include them as additional headers in the response.](https://github.com/articulate/paperplane/blob/master/lib/error.js#L17)  Below is a cheap example of how that might look:
```js
const Boom = require('boom')
const http = require('http')
const { logger, mount } = require('paperplane')

const app = () => {
  const err = Boom.unauthorized()
  err.headers = { 'www-authenticate': 'Basic' }
  return Promise.reject(err)
}

http.createServer(mount({ app })).listen(3000, logger)
```

**Comment by rakeshpai** [comment]
That totally worked. Thanks a ton.

Should've looked at the code. So clean!
