### ISSUE TITLE
Add flushHeaders()

### ISSUE THREAD

**Issue by tziem** [articulate/paperplane#62]
If the response body is an instance of a stream, the headers should be flushed before the pipe method is called.

In writeHTTP.js:
```
if (body instanceof Stream) {
    res.flushHeaders()
    return body.pipe(res)
}
```

**Comment by flintinatux** [comment]
👋 Hey @tziem!  Thanks for posting the issue.  We're not actively maintaining this library, but please feel free to create a PR for it.  If it checks out ok and has good tests, we can make a new release.

**Comment by tziem** [comment]
Hi @flintinatux, I don't need the requested change anymore.
See my comment in #63.
